#ifndef INCUBATOR_ENUMSCREENTYPE_H
#define INCUBATOR_ENUMSCREENTYPE_H
namespace Incubator
{
enum EnumScreenType
{
  SCREEN_TYPE_DISPLAY_OFF,
  SCREEN_TYPE_MAIN,
  SCREEN_TYPE_MENU,
  SCREEN_TYPE_SETTINGS,
  SCREEN_TYPE_SENSORS_STATUS,
  SCREEN_TYPE_INCUBATOR_SETTINGS,
  SCREEN_TYPE_TIME_SETTINGS,
  SCREEN_TYPE_DEFAULTS_SETTINGS,
  SCREEN_TYPE_TEMPERATURE_SETTINGS,
  SCREEN_TYPE_HUMIDITY_SETTINGS,
  SCREEN_TYPE_DATA_SET_TEMPERATURE,
  SCREEN_TYPE_DATA_SET_TEMPERATURE_LAST_DAYS,
  SCREEN_TYPE_DATA_SET_HUMIDITY,
  SCREEN_TYPE_DATA_SET_HUMIDITY_LAST_DAYS,
  SCREEN_TYPE_CURRENT_TIME_SETTINGS,
  SCREEN_TYPE_DATA_SET_CURRENT_DAY,
  SCREEN_TYPE_DATA_SET_CURRENT_HOUR,
  SCREEN_TYPE_DATA_SET_CURRENT_MINUTE,
  SCREEN_TYPE_INCUBATOR_TIME_SETTINGS,
  SCREEN_TYPE_DATA_SET_TOTAL_DAY_COUNT,
  SCREEN_TYPE_DATA_SET_LAST_DAY_COUNT,
  SCREEN_TYPE_QUESTION_SAVE,
  SCREEN_TYPE_QUESTION_TIME_RESET,
  SCREEN_TYPE_ADMINISTRATOR_SETTINGS,
  SCREEN_TYPE_TEMPERATURE_PID,
  SCREEN_TYPE_HYSTERISIS_HUMIDITY,
  SCREEN_TYPE_QUESTION_ADMIN_RESET,
  SCREEN_TYPE_DATA_SET_P,
  SCREEN_TYPE_DATA_SET_I,
  SCREEN_TYPE_DATA_SET_D,
  SCREEN_TYPE_DATA_SET_UPPER_HYSTERISIS,
  SCREEN_TYPE_DATA_SET_LOWER_HYSTERISIS,
  SCREEN_TYPE_SIZE
};
} // namespace Incubator

#endif // INCUBATOR_ENUMSCREENTYPE_H
